payload:
  description: The original JSON data, where each row is an element in the original
    file JSON list.
  type: variant
  nullable: false
  is_pk: false
  is_fk: false
  quality:
    null_percen: 0
    unique_percen: 1
  nested_structures: true
_source_file:
  description: source file path.
  type: string
  nullable: false
  is_pk: false
  is_fk: false
  quality:
    null_percen: 0
    unique_percen: 1
_source_file_name:
  description: source file name.
  type: string
  nullable: false
  is_pk: false
  is_fk: false
  quality:
    null_percen: 0
    unique_percen: 1
_source_file_size:
  description: source file size.
  type: bigint
  nullable: false
  is_pk: false
  is_fk: false
  quality:
    null_percen: 0
    unique_percen: 1
_source_file_modified_at:
  description: last modification time of the soource file.
  type: timestamp
  nullable: false
  is_pk: false
  is_fk: false
  quality:
    null_percen: 0
    unique_percen: 1
snapshot_ts:
  description: snapshot date of the file
  type: date
  nullable: false
  is_pk: false
  is_fk: false
  quality:
    null_percen: 0
    unique_percen: 1
file_name_error:
  description: error in the source file name, if present
  type: string
  nullable: true
  is_pk: false
  is_fk: false
  quality:
    null_percen: 0
    unique_percen: 1
ingest_ts:
  description: timestamp when record was ingested
  type: timestamp
  nullable: false
  is_pk: false
  is_fk: false
  quality:
    null_percen: 0
    unique_percen: 1

remaining_payload:
  description: captured data that is not included in the used schema.
  type: variant
  nullable: false
  is_pk: false
  is_fk: false
  quality:
    null_percen: 0
    unique_percen: 0
  nested_structures: true
known_latest_snapshot:
  description: 'Latest snapshot date, required for filtering.'
  type: string
  nullable: false
  is_pk: false
  is_fk: false
  quality:
    null_percen: 0
    unique_percen: 0