id:
  description: "Identifier of the Unit"
  type: string
  nullable: false
  is_pk: true
  is_fk: false
  quality:
    null_percen: 0
    unique_percen: 0

active:
  description: "Whether the unit is active."
  type: string
  nullable: false
  is_pk: false
  is_fk: false
  quality:
    null_percen: 0
    unique_percen: 0

type:
  description: "Type of the Unit, BU or CU."
  type: string
  nullable: false
  is_pk: false
  is_fk: false
  quality:
    null_percen: 0
    unique_percen: 0

symbole:
  description: "Symbole of the unit."
  type: string
  nullable: false
  is_pk: false
  is_fk: false
  quality:
    null_percen: 0
    unique_percen: 0

name:
  description: "Name of the unit."
  type: string
  nullable: false
  is_pk: false
  is_fk: false
  quality:
    null_percen: 0
    unique_percen: 0

society:
  description: "Society which this Unit belongs to."
  type: variant
  nullable: false
  is_pk: false
  is_fk: true
  quality:
    null_percen: 0
    unique_percen: 0
    referential_integrity: Should be granted.
  nested_structures: true

entity:
  description: "Entity which this unit belongs to."
  type: variant
  nullable: false
  is_pk: false
  is_fk: true
  quality:
    null_percen: 0
    unique_percen: 0
    referential_integrity: Should be granted.
  nested_structures: true

manager:
  description: "List of managers that manage associated with the unit."
  type: variant
  nullable: false
  is_pk: false
  is_fk: true
  quality:
    null_percen: 0
    unique_percen: 0
    referential_integrity: Should be granted.
  nested_structures: true

hrbp:
  description: "List of Human Resources Manager associated with this Unit."
  type: variant
  nullable: false
  is_pk: false
  is_fk: true
  quality:
    null_percen: 0
    unique_percen: 0
    referential_integrity: Should be granted.
  nested_structures: true

calendar:
  description: "Calendar code of the unit."
  type: string
  nullable: false
  is_pk: false
  is_fk: false
  quality:
    null_percen: 0
    unique_percen: 0

staff_manager:
  description: "List of staff managers associated with the unit."
  type: variant
  nullable: false
  is_pk: false
  is_fk: true
  quality:
    null_percen: 0
    unique_percen: 0
    referential_integrity: Should be granted.
  nested_structures: true

whoz_key_A:
  description: ""
  type: string
  nullable: false
  is_pk: false
  is_fk: false
  quality:
    null_percen: 0
    unique_percen: 0
