certification_id:
  description: 'Identifier of the certification associated with the aptitude.'
  type: string
  nullable: false
  is_pk: true
  is_fk: true
  quality:
    null_percen: 0
    unique_percen: 0ç
    referential_integrity: Should be granted.

profile_id:
  description: 'Identifier of the profile associated with the certification aptitude.'
  type: string
  nullable: false
  is_pk: true
  is_fk: true
  quality:
    null_percen: 0
    unique_percen: 0ç
    referential_integrity: Should be granted.

aptitude_id:
  description: 'Identifier of the aptitude associated with the certification.'
  type: string
  nullable: false
  is_pk: false
  is_fk: true
  quality:
    null_percen: 0
    unique_percen: 0ç
    referential_integrity: Should be granted.

concept_id:
  description: 'Identifier of the concept associated with the aptitude.'
  type: string
  nullable: false
  is_pk: false
  is_fk: true
  quality:
    null_percen: 0
    unique_percen: 0ç
    referential_integrity: Should be granted.

name:
  description: 'Name of the aptitude associated with the certification.'
  type: string
  nullable: false
  is_pk: false
  is_fk: false
  quality:
    null_percen: 0
    unique_percen: 0

type:
  description: 'Type or category of the aptitude.'
  type: string
  nullable: false
  is_pk: false
  is_fk: false
  quality:
    null_percen: 0
    unique_percen: 0
